language: scala
jdk: openjdk8
scala: 2.11.12
sudo: false

# Fail if autoformat makes changes
script: sbt test && tools/scalarifail

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
